name: tests
run-name: Tests & health checker - ${{ github.run_number }}


on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run tests and healthChecker
        run: docker compose up --wait --wait-timeout 120 app

      - name: Shutdown all services
        if: always()
        run: docker compose down

      - name: View logs on failure
        if: failure()
        run: docker compose logs
